import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Providers } from "./provider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { cookies, headers } from "next/headers";
import AuthInitializer from "@/components/auth/auth-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <Providers>


          <Header />
          <div className="max-w-7xl mx-auto">
            <AuthInitializer />
            {children}
          </div>
          <Footer />
        </Providers>

      </body>
    </html >
  )
}
